// <auto-generated />
using System;
using CalendarChanger.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarChanger.Migrations
{
    [DbContext(typeof(CalendarContext))]
    [Migration("20251108110538_AddCalendarSettingsAndRoosterUrls")]
    partial class AddCalendarSettingsAndRoosterUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("CalendarChanger.Models.CalendarFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncludeTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarFilters");
                });

            modelBuilder.Entity("CalendarChanger.Models.CalendarSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarSettings");
                });

            modelBuilder.Entity("CalendarChanger.Models.EventMeta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CustomEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CustomStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("OriginalEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("OriginalStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CalendarChanger.Models.RoosterUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoosterUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
